### ISSUE TITLE
Add UUIDs to zine

### ISSUE THREAD

**Issue by faun** [zinedistro/zinedistro#47]

**Comment by faun** [comment]
Another alternative is to provide a unique constraint on the zine title and key off the slug.

**Comment by gwincr11** [comment]
What is the intended us of the identifier. If it is for URL's then you should strive to make it friendly. A simple way is to use the id of the zine followed by the title id-title. Then you can call find and convert the param to an int. This offers some SEO benefits and is simple to implement.

**Comment by faun** [comment]
That is captured in #44. I'm going to close this because when moving features from pivotal tracker, I let some of the half-baked terrible ideas through.
