### ISSUE TITLE
Add UUIDs to author

### ISSUE THREAD

**Issue by faun** [zinedistro/zinedistro#48]

**Comment by faun** [comment]
It's also an option to key off the author's name, since that's unique.

**Comment by faun** [comment]
Good idea?

**Comment by gwincr11** [comment]
It depends on what you are keying for, id should probably be the primary key, but you could index the database on another column. Names are not always unique, one option although you are currently not using it would be email address. Email addresses are useful to collect for other things and are always unique.

**Comment by faun** [comment]
The authors are more of a placeholder for being able to cross-reference zines distributed by the same author. The authors have very little info stored about them. They consist pretty much of just a name and the association is what defines which zines belong to an author. The primary consideration here is a collision of resources on S3, but as long as there are no two apps pointing to the same bucket, everything will be fine. The other situation where UUIDs are useful is when there are multiple database instances, but conversation gets us into dangerous YAGNI territory. I think I'm going to close these UUID issues and re-open them if we ever see fit.

**Comment by gwincr11** [comment]
What are you storing on s3, couldn't you just put it in a folder for the name of the zine followed by the zines id number? that seems pretty simple since the id number auto increments you will never collide and the name will make it easy to find in s3 in the future.
